shipmonk-rnd/phpstan-rules

src/Rule/ForbidUnusedExceptionRule.php

- unreliable in newer phpstan versions due to fully static reflection

ForbidUnusedExceptionRule: remove is_a function

---

composer.json
src/Rule/UselessPrivatePropertyNullabilityRule.php
tests/Rule/UselessPrivatePropertyNullabilityRuleTest.php

Solution from https://github.com/phpstan/phpstan-src/pull/1480#issuecomment-1169960148

UselessPrivatePropertyNullabilityRule: drop extension provider

---

src/Rule/ForbidAssignmentNotMatchingVarDocRule.php
tests/Rule/data/ForbidAssignmentNotMatchingVarDocRule/code.php

ForbidAssignmentNotMatchingVarDocRule: fix check-shape-only with iterable

---

src/Rule/UselessPrivatePropertyNullabilityRule.php
src/Visitor/ClassPropertyAssignmentVisitor.php

Before:
```
Assign <-> var (PropFetch)
-> expr (Expr)
```
Now:
```
Assign -> var (PropFetch)
↓
-> expr (Expr)
```

ClassPropertyAssignmentVisitor: drop useless AST cycle

---

src/Rule/UselessPrivatePropertyNullabilityRule.php
tests/Rule/data/UselessPrivatePropertyNullabilityRule/code.php

When the property is promoted, null value can be assigned to it when an instance is created so it shouldn't be reported as never having null value.

Fix UselessPrivatePropertyNullabilityRule false-positive for promoted properties

---

src/Rule/ForbidUnusedMatchResultRule.php
tests/Rule/data/ForbidUnusedMatchResultRule/code.php

Match can contain only assignments like this:
```php
match ($int) {
0 => $a = 'x',
1 => $b = 'y',
};
```
Then is not necessary to trigger `ForbidUnusedMatchResultRule`.

Match can contain only assignments

---

src/Rule/EnforceNativeReturnTypehintRule.php
tests/Rule/EnforceNativeReturnTypehintRuleTest.php
tests/Rule/data/EnforceNativeReturnTypehintRule/code-80.php
tests/Rule/data/EnforceNativeReturnTypehintRule/code-81.php
tests/Rule/data/EnforceNativeReturnTypehintRule/code-82.php
tests/Rule/data/EnforceNativeReturnTypehintRule/code-enum.php

- _No type hint for resources is added, as this would prevent moving from resources to objects for existing extensions, which some have already done (e.g. GMP)._
- https://wiki.php.net/rfc/scalar_type_hints

EnforceNativeReturnTypehintRule: resource not typehintable & fix self|self

---

src/Rule/EnforceReadonlyPublicPropertyRule.php
tests/Rule/EnforceReadonlyPublicPropertyRuleTest.php
tests/Rule/data/EnforceReadonlyPublicPropertyRule/code-80.php
tests/Rule/data/EnforceReadonlyPublicPropertyRule/code-81.php

Resolves https://github.com/shipmonk-rnd/phpstan-rules/issues/86

enforceReadOnlyPublicProperty: fix false positive on PHP <= 8.0

---

.github/workflows/checks.yml
.gitignore
composer.lock

To prevent CI failures on new PRs due to new stuff being reported in latest phpstan.

CI: static analysis to use composer.lock, matrix only for tests

---

README.md

Adding Brick classes here was a good inspiration, thanks for that!
However:
- We can remove `DateTimeInterface` from here... the array is merged with the default configuration from `rules.neon` anyway so this way `DateTimeInterface` actually gets into `ForbidIdenticalClassComparisonRule` twice, I checked.
- `Brick\Money` doesn't exist, it's `Brick\Money\Money` and I think it's better to use the interface instead anyway to also detect `Brick\Money\RationalMoney`.
- `BigInteger`, `BigDecimal` and `BigRational` all extend `BigNumber` anyway so they're redundant.
- `ramsey/uuid` is a very commonly used library and I almost forgot to add `UuidInterface` into my config.

Improve forbidIdenticalClassComparison example

---

README.md

Ref: https://github.com/shipmonk-rnd/phpstan-rules/pull/104#issuecomment-1517496504

Readme: how to not include default array config

---

src/Rule/ForbidCheckedExceptionInYieldingMethodRule.php
tests/Rule/ForbidCheckedExceptionInYieldingMethodRuleTest.php

I don't know what implicit throw points are, but PHPStan creates them any many places and if `Throwable` is considered a checked exception, this rule will emit lot of false positives.

ForbidCheckedExceptionInYieldingMethodRule: ignore implicit throw points

---

src/Rule/EnforceNativeReturnTypehintRule.php
tests/Rule/data/EnforceNativeReturnTypehintRule/code-82.php

Based on https://github.com/shipmonk-rnd/phpstan-rules/pull/62#issuecomment-1492880348

enforceNativeReturn: fix wrong never suggestion

---

README.md
composer.json
composer.lock
phpcs.xml.dist
phpstan.neon.dist
rules.neon
src/Extension/ImmediatelyCalledCallableThrowTypeExtension.php
src/Rule/ForbidCheckedExceptionInCallableRule.php
src/Visitor/ImmediatelyCalledCallableVisitor.php
tests/Extension/ImmediatelyCalledCallableThrowTypeExtensionTest.php
tests/Extension/data/ImmediatelyCalledCallableThrowTypeExtension/code.php
tests/Extension/data/ImmediatelyCalledCallableThrowTypeExtension/extension.neon
tests/Rule/ForbidCheckedExceptionInCallableRuleTest.php
tests/Rule/data/ForbidCheckedExceptionInCallableRule/code.php
tests/Rule/data/ForbidCheckedExceptionInCallableRule/no-implicit-throws.neon
tests/Rule/data/ForbidCheckedExceptionInCallableRule/visitor.neon

- disallows throwing checked exceptions in Closures and First class callables as those just return callback which can be called any time (thus cannot be tracked by phpstan)
- allows configuration of functions/methods where some callable argument is immediatelly called, then any checked exception in such callable is property tracked!
- this is a must if you use something like `EntityManager::transactional`

ForbidCheckedExceptionInCallableRule

---

src/Extension/ImmediatelyCalledCallableThrowTypeExtension.php
tests/Extension/data/ImmediatelyCalledCallableThrowTypeExtension/code.php
tests/Extension/data/ImmediatelyCalledCallableThrowTypeExtension/extension.neon
tests/Rule/data/ForbidCheckedExceptionInCallableRule/code.php
tests/Rule/data/ForbidCheckedExceptionInCallableRule/visitor.neon

**Goal:**
Ensure immediately called callable argument is recognized on any subtype of the class/interface specified in config.
**Example:**
```
immediatelyCalledCallables:
'Doctrine\ORM\EntityManagerInterface::transactional': 0 # immediately called callable argument is recognized on any implementation of EntityManagerInterface
```
- Added test for existing support in`ForbidCheckedExceptionInCallableRule`
- Added missing support to `ImmediatelyCalledCallableThrowTypeExtension`

Immediately Called Callables config & class inheritance

---

.github/workflows/checks.yml

- likely doable once we tag https://github.com/shipmonk-rnd/name-collision-detector as the upcoming version does not need betterreflection

Run tests even with PHP 8.3

---

README.md
src/Rule/AllowComparingOnlyComparableTypesRule.php
tests/Rule/data/AllowComparingOnlyComparableTypesRule/code.php

[Relevant PHP documentation](https://www.php.net/manual/en/language.operators.comparison.php#example-343)

AllowComparingOnlyComparableTypesRule: allow tuple comparison

---

composer.lock

```
- Upgrading nette/schema (v1.2.5 => v1.3.0)
- Upgrading nette/utils (v4.0.3 => v4.0.4)
```
to avoid
```
Warning: Private methods cannot be final as they are never overridden by other classes in /app/vendor/nette/schema/src/Schema/Helpers.php on line 19
Warning: Private methods cannot be final as they are never overridden by other classes in /app/vendor/nette/utils/src/Utils/Reflection.php on line 18
Warning: Private methods cannot be final as they are never overridden by other classes in /app/vendor/nette/utils/src/Utils/Validators.php on line 18
Warning: Private methods cannot be final as they are never overridden by other classes in /app/vendor/nette/utils/src/Utils/ObjectHelpers.php on line 20
```

Update transitive deps (nette/schema, nette/utils)

---

composer-dependency-analyser.php
composer.json
composer.lock

This should prevent errors like #220, now it (properly) [detected](https://github.com/shipmonk-rnd/phpstan-rules/actions/runs/8140512120/job/22245841427#step:5:350) the `nikic/php-parser` as unused:
Package `nikic/php-parser` is bundled inside PHPStan's phar and is loaded from there, so having it in `require` is useless.

composer-dependency-analyser: prepend PHPStan's PharAutoloader to avoid false reports, drop nikic/php-parser

---

tests/Extension/data/ImmediatelyCalledCallableThrowTypeExtension/code.php
tests/Extension/data/ImmediatelyCalledCallableThrowTypeExtension/extension.neon

Ref: https://github.com/phpstan/phpstan-src/pull/3016#issuecomment-2109863645

ImmediatelyCalledCallableThrowTypeExtension: use implicitThrows: false in test

---

bin/verify-inline-ignore.php
composer.json
src/Rule/EnforceNativeReturnTypehintRule.php
src/Rule/ForbidVariableTypeOverwritingRule.php
tests/Rule/EnforceClosureParamNativeTypehintRuleTest.php
tests/Rule/EnforceNativeReturnTypehintRuleTest.php
tests/Rule/EnforceReadonlyPublicPropertyRuleTest.php
tests/Rule/ForbidCheckedExceptionInCallableRuleTest.php

- Better to target specific issue by identifiers than ignoring all (future) errors on that line

Deny `@phpstan-ignore-line` in favour of `@phpstan-ignore`

---

composer.json
composer.lock
src/Rule/EnforceListReturnRule.php
src/Rule/ForbidReturnValueInYieldingMethodRule.php
src/Rule/ForbidUselessNullableReturnRule.php
src/Rule/RequirePreviousExceptionPassRule.php

- bumps lowest phpstan/phpstan from 1.11.0 to 1.12.5 to be able to use new api to resolve the deprecation with preferred way
- eliminates new deprecation https://github.com/phpstan/phpstan-src/commit/23c53a2210b715f672ad3087dd476faf34bdec6e

Remove deprecated ParametersAcceptorSelector::selectFromArgs

---

src/Rule/ForbidCheckedExceptionInCallableRule.php
src/Rule/ForbidCustomFunctionsRule.php
src/Rule/ForbidEnumInFunctionArgumentsRule.php
tests/Rule/data/unknown-symbol.php
tests/UnknownSymbolTest.php

Fix reflection error on unknown symbols

---

src/Rule/ForbidEnumInFunctionArgumentsRule.php
tests/Rule/data/ForbidEnumInFunctionArgumentsRule/code.php

Over the years, PHPStan finally got support to most of the cases, so we can drop most of them.

forbidEnumInFunctionArguments: skip those detected by PHPStan itself

---

src/Rule/ForbidCustomFunctionsRule.php
tests/Rule/data/ForbidCustomFunctionsRule/code.php

Closes https://github.com/shipmonk-rnd/phpstan-rules/issues/287

ForbidCustomFunctionsRule: detect first class callables, anonymous classes and callables in args

---

src/Rule/EnforceReadonlyPublicPropertyRule.php
tests/Rule/EnforceReadonlyPublicPropertyRuleTest.php
tests/Rule/data/EnforceReadonlyPublicPropertyRule/code-84.php

- Closes #300
- https://wiki.php.net/rfc/property-hooks#interaction_with_readonly
> For that reason, a readonly property with a get or set hook is disallowed and will throw a compile error.

EnforceReadonlyPublicProperty: exclude hooked properties

---

src/Visitor/UnusedMatchVisitor.php
tests/Rule/data/ForbidUnusedMatchResultRule/code.php

Implicitly returning result of match using an arrow function was not counted as used.

ForbidUnusedMatchResultRule: count match implicitly returned by arrow function as used

---

tests/Rule/data/ForbidCheckedExceptionInCallableRule/code.php

To support PHPStan's enhanced dead code detection in closures (phpstan/phpstan-src#4148).

ForbidCheckedExceptionInCallableRuleTest: Split test methods into individual test cases
