shipmonk-rnd/phpstan-rules

README.md, src/Rule/ForbidUnusedMatchResultRule.php, src/Visitor/UnusedMatchVisitor.php, tests/Rule/ForbidUnusedMatchResultRuleTest.php, tests/Rule/data/ForbidUnusedMatchResultRule/code.php, tests/Rule/data/ForbidUnusedMatchResultRule/unused-match-visitor.neon
Related: https://github.com/phpstan/phpstan-src/pull/1726
=> ForbidUnusedMatchResultRule

README.md, composer.json, tests/Rule/AllowNamedArgumentOnlyInAttributesRuleTest.php
Related: https://github.com/composer/composer/pull/10960
=> Install as dev dependency

composer.json
- theoretically, we could change the codebase to support 7.3, for now lets just define current state
=> composer: require php ^7.4|^8.0

composer.json
https://github.com/phpstan/extension-installer
=> Support phpstan/extension-installer

README.md
https://github.com/shipmonk-rnd/phpstan-rules/pull/72
=> Readme: mention extension-installer

.github/workflows/lint.yml, phpcs.xml.dist
Inspired by https://github.com/spaze/coding-standard/blob/97d1893ed85464613ecf047459f0e4ff5b264936/.github/workflows/xml.yml
=> CI: lint phpcs xml ruleset

composer.lock, phpcs.xml.dist
=> Update slevomat/coding-standard: from 8.11.1 to 8.12.1

composer.lock, src/Rule/ForbidProtectedEnumMethodRule.php
=> Update phpstan/phpstan: from 1.10.14 to 1.10.15

composer.lock, src/Rule/ForbidEnumInFunctionArgumentsRule.php
Supersedes https://github.com/shipmonk-rnd/phpstan-rules/pull/164
=> PHPStan: bump from 1.10.32 to 1.10.36

composer.json, phpstan.neon.dist
https://twitter.com/janedbal/status/1708849962837008474
=> Enable PHPStan clickable links

phpstan.neon.dist, src/Rule/ForbidUnusedMatchResultRule.php
=> forbidUnusedMatchResult: fix void issue in PHPStan >= 1.10.49

tests/RuleTestCase.php
Simplier approach to have proper identifiers than [this attempt](https://github.com/shipmonk-rnd/phpstan-rules/pull/173/files#diff-378d028d18c973d67f895c45f6b530a65178cb1e1ec8e80dad8f543b2bf2e5e4R18)
=> Assert all errors has proper identifier

src/Rule/ForbidEnumInFunctionArgumentsRule.php, tests/Rule/data/ForbidEnumInFunctionArgumentsRule/code.php
=> forbidEnumInFunctionArguments: allow array_unique($enums, SORT_REGULAR)

composer.json, composer.lock, src/Rule/ForbidCheckedExceptionInCallableRule.php
Introduced by https://github.com/phpstan/phpstan-src/commit/7eb66f6bd643fc95f8353b3b273c29514ddd8619
=> Fix compatibility with PHPStan >=1.10.51

src/Rule/ForbidMethodCallOnMixedRule.php, tests/Rule/data/ForbidMethodCallOnMixedRule/code.php
Available since phpstan 1.10.33: https://github.com/phpstan/phpstan-src/pull/2598
=> ForbidMethodCallOnMixedRule: use ?-> in error message for nullsafe

README.md
=> immediatelyCalledCallables: mention immediate closure call issue

composer-dependency-analyser.php, composer.json, composer.lock
- https://github.com/shipmonk-rnd/composer-dependency-analyser
=> Add composer-dependency-analyser

composer.json, composer.lock
- https://github.com/editorconfig-checker/editorconfig-checker.php/releases/tag/10.6.0
=> editorconfig-checker/editorconfig-checker: require 10.6.0

README.md
- ref https://github.com/phpstan/phpstan-src/pull/2840
=> Readme: mention reportAnyTypeWideningInVarTag extra strictness

src/Rule/ForbidNotNormalizedTypeRule.php, tests/Rule/data/ForbidNotNormalizedTypeRule/code.php
- Implemented idea from @derrabus: https://github.com/phpstan/phpstan/issues/8842#issuecomment-2024972047
=> ForbidNotNormalizedTypeRule: check even multi-catch statements

README.md
Ref: https://github.com/phpstan/phpstan/issues/10565#issuecomment-2004351214
=> forbidCheckedExceptionInCallable: remove limitation

composer.json, composer.lock, phpstan.neon.dist
Working out of the box!
https://github.com/shipmonk-rnd/dead-code-detector
=> Initialize dead-code detector

composer.json, composer.lock, phpstan.neon.dist, src/Rule/EnforceClosureParamNativeTypehintRule.php, src/Rule/EnforceIteratorToArrayPreserveKeysRule.php, src/Rule/ForbidCheckedExceptionInCallableRule.php, src/Rule/ForbidCheckedExceptionInYieldingMethodRule.php, src/Rule/ForbidNotNormalizedTypeRule.php, src/Rule/ForbidProtectedEnumMethodRule.php, src/Rule/ForbidReturnValueInYieldingMethodRule.php, src/Rule/RequirePreviousExceptionPassRule.php, src/Rule/UselessPrivatePropertyDefaultValueRule.php, src/Rule/UselessPrivatePropertyNullabilityRule.php
To catch things like https://github.com/phpstan/phpstan-src/commit/23c53a2210b715f672ad3087dd476faf34bdec6e
=> Use phpstan-deprecation-rules

.github/workflows/checks.yml
=> CI: use checkout v4

rules.neon
Nothing special, just missing argument.
=> ForbidCastRule: fix custom blacklist
